# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

version: "3.8"

services:
  nginx:
    build:
      context: ../../../Settings/V1/gateway/
      dockerfile: Dockerfile
    environment:
      ADMIN_API_VIRTUAL_NAME: "${ADMIN_API_VIRTUAL_NAME:-adminapi}"
    ports:
      - "443:443"
      - "80:80"
    container_name: ed-fi-gateway-adminapi-packaged
    restart: always
    hostname: nginx
    volumes:
      - ../../../Settings/ssl:/ssl/
      - ../../../Settings/V1/gateway/adminapi-packaged.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - adminapi

  adminapi:
    build:
      context: ../../../
      dockerfile: api.pgsql.Dockerfile
      args:
        ADMIN_API_VERSION: ${ADMIN_API_VERSION:-1.4.2}
    environment:
      ADMIN_POSTGRES_HOST: db-admin
      POSTGRES_PORT: 5432
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASEENGINE: "PostgreSql"
      API_MODE: ${API_MODE}
      AUTHORITY: ${AUTHORITY}
      ISSUER_URL: ${ISSUER_URL}
      SIGNING_KEY: ${SIGNING_KEY}
      ADMIN_API_VIRTUAL_NAME: ${ADMIN_API_VIRTUAL_NAME:-adminapi}
      ODS_API_VERSION: ${ODS_API_VERSION}
      AppSettings__AdminApiMode: ${ADMINAPI_MODE:-V1}
      EnableDockerEnvironment: true
      SwaggerSettings__EnableSwagger: true
      EnableSwagger: true
      Authentication__AllowRegistration: true
# ---
      ADMIN_API_VERSION: ${ADMIN_API_VERSION}
      AppSettings__DatabaseEngine: "PostgreSql"
      AppSettings__DefaultPageSizeLimit: ${PAGING_LIMIT:-25}
      AppSettings__DefaultPageSizeOffset: ${PAGING_OFFSET:-0}
      AppSettings__EnableApplicationResetEndpoint: false
      AppSettings__EncryptionKey: "TDMyNH0lJmo7aDRnNXYoSmAwSXQpV09nbitHSWJTKn0="
      AppSettings__MultiTenancy: false
      AppSettings__PathBase: ${ADMIN_API_VIRTUAL_NAME:-adminapi}
      AppSettings__PreventDuplicateApplications: "${PREVENT_DUPLICATE_APPLICATIONS:-false}"
      Authentication__IssuerUrl: ${ISSUER_URL}
      Authentication__SigningKey: ${SIGNING_KEY}
      AdminConsoleSettings__CorsSettings__AllowedOrigins: "${ALLOWED_ORIGINS:-https://localhost}"
      AdminConsoleSettings__CorsSettings__EnableCors: "${ENABLE_CORS:-false}"
      ConnectionStrings__EdFi_Admin: "host=db-admin;port=${POSTGRES_PORT};username=${POSTGRES_USER};password=${POSTGRES_PASSWORD};database=EdFi_Admin;pooling=true"
      ConnectionStrings__EdFi_Security: "host=db-admin;port=${POSTGRES_PORT};username=${POSTGRES_USER};password=${POSTGRES_PASSWORD};database=EdFi_Security;pooling=true"
      IpRateLimiting__EnableEndpointRateLimiting: ${IPRATELIMITING__ENABLEENDPOINTRATELIMITING:-false}
      IpRateLimiting__StackBlockedRequests: ${IPRATELIMITING__STACKBLOCKEDREQUESTS:-false}
      IpRateLimiting__RealIpHeader: ${IPRATELIMITING__REALIPHEADER:-X-Real-IP}
      IpRateLimiting__ClientIdHeader: ${IPRATELIMITING__CLIENTIDHEADER:-X-ClientId}
      IpRateLimiting__HttpStatusCode: ${IPRATELIMITING__HTTPSTATUSCODE:-429}
      IpRateLimiting__IpWhitelist: ${IPRATELIMITING__IPWHITELIST:-[]}
      IpRateLimiting__EndpointWhitelist: ${IPRATELIMITING__ENDPOINTWHITELIST:-[]}
      Log4NetCore__Log4NetConfigFileName: "./log4net.config"

    depends_on:
      - db-admin
    restart: always
    hostname: ${ADMIN_API_VIRTUAL_NAME:-adminapi}
    container_name: adminapi-packaged
    healthcheck:
      test: ${ADMIN_API_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3

  db-admin:
    image: edfialliance/ods-admin-api-db:v1.4.3
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      API_MODE: ${API_MODE}
    ports:
      - "5401:5432"
    volumes:
      - vol-db-admin-adminapi:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-admin-adminapi

volumes:
  vol-db-admin-adminapi:
    driver: local
    name: vol-db-admin-adminapi
